# Generated by Django 3.0.2 on 2020-02-01 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Enter the about page of the fest here')),
                ('logo', models.ImageField(blank=True, upload_to='')),
                ('identifier', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupName', models.CharField(help_text='Name of the event group', max_length=255, unique=True)),
                ('groupId', models.CharField(help_text='ID by which group will be identified', max_length=20, unique=True)),
                ('logo', models.ImageField(blank=True, upload_to='event_category_images/')),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=50)),
                ('question', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
            },
        ),
        migrations.CreateModel(
            name='MajorAttractions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(help_text='Enter the description of the attraction here')),
                ('logo', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Sponsors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='sponsors/')),
                ('url', models.EmailField(blank=True, help_text='URL of the sponsor', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='TeamCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter name of the team category here', max_length=100)),
                ('teamId', models.CharField(help_text='Enter category ID', max_length=50, unique=True)),
                ('team_image', models.ImageField(blank=True, upload_to='team_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Workshops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workshopName', models.CharField(help_text='Enter name of workshop', max_length=100, unique=True)),
                ('workshopId', models.CharField(help_text='Enter the ID of the workshop', max_length=50)),
                ('logo', models.ImageField(blank=True, upload_to='workshop_images/')),
                ('description', models.TextField(help_text='Enter short description of the workshop')),
                ('date_time', models.DateTimeField()),
                ('venue', models.CharField(max_length=50)),
                ('registration_open', models.BooleanField(default=True)),
                ('registration_link', models.CharField(blank=True, help_text='Enter the registration link here', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the member here', max_length=50, unique=True)),
                ('position', models.CharField(help_text='Enter the position of the person', max_length=50)),
                ('profile_img', models.ImageField(blank=True, upload_to='members/')),
                ('choice', models.CharField(choices=[('GLUG', "GNU/Linux Users' Group"), ('CCA', 'Centre for Cognitive Activities'), ('SAE', 'SAE'), ('MNTC', 'Maths n Tech Club'), ('REC', 'RECursion')], default='GLUG', max_length=5)),
                ('team', models.ManyToManyField(to='flow.TeamCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(help_text='Enter the name of the event', max_length=50, unique=True)),
                ('eventId', models.CharField(help_text='Enter the ID of the event', max_length=50)),
                ('logo', models.ImageField(blank=True, upload_to='event_images/')),
                ('description', models.TextField(help_text='Enter short description of the event')),
                ('problem_statement', models.TextField(blank=True, help_text='Enter the problem statement of the event here')),
                ('date_time', models.DateTimeField()),
                ('venue', models.CharField(blank=True, max_length=50)),
                ('contact', models.CharField(max_length=20)),
                ('registration_open', models.BooleanField(default=True)),
                ('registration_link', models.CharField(blank=True, help_text='Enter the registration link here', max_length=50)),
                ('eventGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flow.EventCategory')),
            ],
        ),
    ]
