# Generated by Django 2.2.4 on 2020-02-02 09:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshops',
            name='contact',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='events',
            name='contact',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='majorattractions',
            name='logo',
            field=models.ImageField(blank=True, upload_to='mjr_attrs/'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='position',
            field=models.CharField(blank=True, help_text='Enter the position of the person', max_length=50),
        ),
    ]
